<?php

$path_tablas = array(
    'Prerequisitos' => 'files/Prerrequisitos.csv',
    'Notas' => 'files/Notas.csv',
    'Planes' => 'files/Planes.csv',
    'Asignaturas' => 'files/Asignaturas.csv',
    'Estudiantes' => 'files/Estudiantes.csv',
    'Planeacion' => 'files/Planeacion.csv',
    "Docentes_Planificados" => 'files/Docentes_Planificados.csv'
);

$tablas_iniciales = array(
    'prerequisitos' => "PLAN CHAR(3),
        ASIGNATURA_ID TEXT,
        ASIGNATURA TEXT,
        NIVEL INT,
        UNO TEXT,
        DOS TEXT",

    'notas' => "CODIGO_PLAN TEXT,
        PLAN TEXT,
        COHORTE TEXT,
        SEDE TEXT,
        RUN VARCHAR(10),
        DV CHAR(1),
        NOMBRES TEXT,
        APELLIDO_PATERNO TEXT,
        APELLIDO_MATERNO TEXT,
        NUMERO_DE_ALUMNO INT,
        PERIODO_ASIGNATURA TEXT,
        CODIGO_ASIGNATURA TEXT,
        ASIGNATURA TEXT,
        CONVOCATORIA TEXT,
        CALIFICACION TEXT,
        NOTA TEXT",

    'planes' => "CODIGO_PLAN CHAR(3),
        FACULTAD TEXT,
        CARRERA TEXT,
        PLAN TEXT,
        JORNADA TEXT,
        SEDE TEXT,
        GRADO TEXT,
        MODALIDAD TEXT,
        INICIO_VIGENCIA TEXT",

    'asignaturas' => "PLAN CHAR(3),
        ASIGANTURA_ID TEXT,
        ASIGNATURA TEXT,
        NIVEL INT",

    'estudiantes' => "CODIGO_PLAN CHAR(3),
        CARRERA TEXT,
        COHORTE TEXT,
        NUMERO_DE_ALUMNO INT,
        BLOQUEO CHAR(1),
        CAUSAL_BLQUEO TEXT,
        RUN VARCHAR(10),
        DV CHAR(1),
        NOMBRES TEXT,
        PRIMER_APELLIDO TEXT,
        SEGUNDO_APELLIDO TEXT,
        LOGRO TEXT,
        FECHA_LOGRO VARCHAR(7),
        ULTIMA_CARGA VARCHAR(7) NULL",

    'planeacion' => "PERIODO VARCHAR(7),
        SEDE TEXT,
        FACULTAD TEXT,
        CODIGO_DEPARTAMENTO CHAR(5),
        DEPARTAMENTO TEXT,
        ID_ASIGNATURA TEXT,
        ASIGNATURA TEXT,
        SECCION INT,
        DURACION CHAR(1),
        JORNADA TEXT,
        CUPOS INT,
        INSCRITOS INT,
        DIA TEXT,
        HORA_INICIO TIME,
        HORA_FINAL TIME,
        FECHA_INICIO TEXT,
        FECHA_FIN TEXT,
        LUGAR TEXT,
        EDIFICIO TEXT,
        PROFESOR_PRINCIPAL TEXT,
        RUN VARCHAR(10),
        NOMBRE_DOCENTE TEXT,
        APELLIDO_DOCENTE TEXT,
        SEGUNDO_APELLIDO_DOCENTE TEXT,
        JERARQUIZACION TEXT",

    'docentes_planificados' => "RUN VARCHAR(10),
        NOMBRE TEXT,
        APELLIDO_PATERNO TEXT,
        TELEFONO INT,
        EMAIL_PERSONAL TEXT,
        EMAIL_INSTITUCIONAL TEXT,
        DEDICACION INT,
        CONTRATO TEXT,
        DIURNO TEXT,
        VESPERTINO TEXT,
        SEDE TEXT,
        CARRERA TEXT,
        GRADO_ACADEMICO TEXT,
        JERARQUIA TEXT,
        CARGO TEXT,
        ESTAMENTO TEXT"
);

?>