name: Create Database and Run PHP Script

on: [push]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Create database grupo49
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE grupo49;"
      env:
        PGPASSWORD: postgres

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Puedes cambiar la versión de PHP según tus necesidades

    - name: Run loader.php
      run: php BananerApp/src/loader/loader.php